brewbros/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.posts, name="posts"),
    path("post/<int:pk>/", views.post, name="post"),
    path("tag/<int:tag_id>/", views.filter_by_tag, name="filter_by_tag"),
]

brewbros/brewbros/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('auth/', include("myauth.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path('payment/', include('payment.urls', namespace='payment')),
    path("products/", include("products.urls")),
    path("blog/", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

brewbros/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

brewbros/orders/urls.py
# from django.conf.urls import url

from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_create, name='order_create'),
]

brewbros/cart/forms.py
from django import forms

CHOICES = [(i, str(i)) for i in range(1, 16)]
# CHOICES = list(map(lambda x: (x, str(x)), range(1, 16)))


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    # quantity.widget.attrs.update({'class': 'form-control'})

brewbros/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        cart.add(product=product, quantity=data['quantity'], update_quantity=data['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

brewbros/cart/templates/cart/detail.html
{% extends 'products/base.html' %}
{% load static %}

{%  block title %}
  Cart
{%  endblock %}

{% block body %}

<div class="ftco-section">
  <div class="container">
	{% if cart|length == 0 %}
        <br>
          <div class="container">
            <div class="row">
                  <table class="table">
                      <tr class="text-center">
                        <th>Your CART is empty</th>
                        <th></th>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Qty</th>
                        <th>Total</th>
                      </tr>
                  </table>
              </div>
    		</div>
        </div>

    {% else %}
        <br>
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="cart-list">
                  <table class="table">
                      <tr class="text-center">
                        <th>Your CART</th>
                        <th></th>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Qty</th>
                        <th>Total</th>
                      </tr>
                    <tbody>
                     {% for item in cart %}
                       {% with product=item.product %}
                         <tr class="text-center">
                           <td class="product-remove"><a href="{% url 'cart:cart_remove' product.id %}"><span class="icon-close"></span></a></td>
                           <td class="image-prod"><div class="img" style="background-image:url({% static 'products/images/bag-99.jpg' %});"></div></td>
                           <td class="product-name">
                             <h3>{{ product.name }} </h3>
                             <p class="text-primary">{{ product.kind }}</p>
                           </td>
                           <td class="price">${{ item.price }}</td>
                           <td class="quantity">

                             <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                 {% csrf_token %}
                                 {{ item.update_quantity_form.quantity }}
                                 {{ item.update_quantity_form.update }}
                               <input type="submit" class="btn btn-primary btn-outline-primary " value="update">
                             </form>
                           </td>
                            <td class="total">${{ item.total_price }}</td>
						       </tr><!-- END TR-->
                              {% endwith %}
                            {% endfor %}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-end">
    			<div class="col col-lg-3 col-md-6 mt-5 cart-wrap">
    				<div class="cart-total mb-3">
{#    					<h3>Cart Total</h3>#}
    					<p class="d-flex">
    						<span>Subtotal</span>
    						<span>${{ cart.get_total_price }}</span>
    					</p>
    					<p class="d-flex">
    						<span>Delivery</span>
    						<span>$0.00</span>
    					</p>
    					<p class="d-flex">
    						<span>Discount</span>
    						<span>$0.00</span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span>${{ cart.get_total_price}}</span>
    					</p>
    				</div>
                    <p class="text-center"><a href="{% url "orders:order_create" %}" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
    			</div>
    		</div>
			</div>
    {% endif %}
   </div>

{% endblock %}