brewbros/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.posts, name="posts"),
    path("post/<int:pk>/", views.post, name="post"),
    path("tag/<int:tag_id>/", views.filter_by_tag, name="filter_by_tag"),
]

brewbros/brewbros/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('auth/', include("myauth.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path('payment/', include('payment.urls', namespace='payment')),
    path("products/", include("products.urls")),
    path("blog/", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

brewbros/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

brewbros/myauth/urls.py
from django.urls import path

from .views import (
    secret_view,
    MeView,
    LoginView,
    LogoutView,
    UserCreationView,
)

app_name = "myauth"

urlpatterns = [
    path("secret/", secret_view, name="secret"),
    path("me/", MeView.as_view(), name="me"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreationView.as_view(), name="register")
]

brewbros/products/urls.py
from django.urls import path
from .views import (shop, home, ProductDetailView)

app_name = "products"

urlpatterns = [
    path("", home, name="home"),
    path("shop/", shop, name="shop"),
    path("<int:pk>/", ProductDetailView.as_view(), name="details"),
]

brewbros/products/models.py
from django.db import models
from typing import TYPE_CHECKING

from django.urls import reverse


class ProductKind(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64, unique=True)
    # class Meta:
    #     ordering = ('name')
    #     verbose_name_plural = 'Kinds'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:filter_by_kind', kwargs={'kind_id': self.pk})


class Product(models.Model):
    kind = models.ForeignKey(ProductKind, on_delete=models.PROTECT, related_name="product")
    name = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    origin = models.ManyToManyField("products.ProductOrigin", related_name="product")
    description = models.TextField(blank=True, null=False)
    archived = models.BooleanField(default=False)
    # created = models.DateTimeField(auto_now_add=True)
    # image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    # available = models.BooleanField(default=True)
    # class Meta:
    #     ordering = ('name')
    #     verbose_name_plural = 'Products'

    if TYPE_CHECKING:
        objects: models.Manager

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:details', args=[self.pk, ])


class ProductProfile(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name="profile")
    degree_of_roast = models.CharField(max_length=64)
    preparation_method = models.TextField(blank=True, null=False)

    def __str__(self):
        return f"Recommended coffee preparation methods: {self.preparation_method}"


class ProductOrigin(models.Model):
    origin = models.CharField(max_length=64)

    def __str__(self):
        return self.origin

    def get_absolute_url(self):
        return reverse('products:filter_by_origin', kwargs={'origin_id': self.pk})

brewbros/products/forms.py
from django import forms
from products.models import ProductKind


class FilterByKindForm(forms.Form):
    choice = forms.ModelChoiceField(queryset=ProductKind.objects.all(), label="",
                                    empty_label="--------------------")

brewbros/products/views.py
from django.http import HttpRequest
from django.shortcuts import render
from django.views.generic import DetailView

from cart.forms import CartAddProductForm
from .forms import FilterByKindForm
from .models import Product, ProductKind


def home(request: HttpRequest):
    return render(request=request, template_name='products/home.html')


def shop(request: HttpRequest):
    main = Product.objects.select_related("kind").prefetch_related("origin").filter(archived=False).order_by(
         "-price", "name").all()
    kind = ProductKind.objects.all()
    form1 = FilterByKindForm()
    if request.method == "POST":
        key = request.POST.get("choice")
        form1.is_valid()
        context = {"form": form1, "products": main.filter(kind=key), "kind": kind, "filter_by": 0}
    else:
        context = {"form": form1, "products": main, "kind": kind, "filter_by": 0}
    return render(request=request, template_name='products/shop.html', context=context)


class ProductDetailView(DetailView):
    template_name = "products/details.html"
    context_object_name = "product"
    cart_product_form = CartAddProductForm()
    queryset = (
        Product
        .objects
        .select_related("profile", "kind")
        .prefetch_related("origin")
    )


def about(request: HttpRequest):
    return render(request=request, template_name='products/index.html')


def article(request: HttpRequest):
    return render(request=request, template_name='products/article.html')

brewbros/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}

        {% endblock %}
    </title>
{#  <link  href="{% static 'products/css/styles.css' %}" rel="stylesheet" />#}

{#    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">#}
{#    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">#}
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="{%  static 'products/css/open-iconic-bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{%  static 'products/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{%  static 'products/css/animate.css' %}" />

    <link rel="stylesheet" href="{%  static 'products/css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{%  static 'products/css/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{%  static 'products/css/magnific-popup.css' %}" />

    <link rel="stylesheet" href="{%  static 'products/css/aos.css' %}" />

    <link rel="stylesheet" href="{%  static 'products/css/ionicons.min.css' %}" />

    <link rel="stylesheet" href="{%  static 'products/css/bootstrap-datepicker.css' %}" />
    <link rel="stylesheet" href="{%  static 'products/css/jquery.timepicker.css' %}" />


    <link rel="stylesheet" href="{%  static 'products/css/flaticon.css' %}" />
    <link rel="stylesheet" href="{%  static 'products/css/icomoon.css' %}" />
    <link rel="stylesheet" href="{%  static 'products/css/style.css' %}" />
  </head>
  <body>

 	<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'products:home' %}">BREW<small>Bros</small></a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item "><a href="{% url 'products:home' %}" class="nav-link ">Home</a></li>
            <li class="nav-item "><a href="{% url 'products:shop' %}" class="nav-link">Shop</a></li>
            <li class="nav-item"><a href="{% url 'blog:posts' %}" class="nav-link">Blog</a></li>

            <li class="nav-item">
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'myauth:me' %}">{{ user.username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'myauth:logout' %}">Logout</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'myauth:register' %}">Register</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'myauth:login' %}">Login</a></li>
            {% endif %}


          <li class="nav-item cart">
            {% with total_items=cart|length %}
               {% if cart|length > 0 %}
               <a href="{% url 'cart:cart_detail' %}" class="nav-link"><span class="icon icon-shopping_cart"></span>
                   <span class="bag d-flex justify-content-center align-items-center"><small>{{ cart|length }}</small></span></a></li>
               {% else %}
                    <a class="nav-link" href="{% url "cart:cart_detail" %}"><span class="icon icon-shopping_cart"></span></a>
               {% endif %}
            {% endwith %}
          </ul>
    </div>
  </div>
</nav>

    {%  block body %}
     <br><br><br><br>
    <h4>Oops, something went wrong!</h4>
    {% endblock %}

 <script src="{%  static 'products/js/jquery.min.js' %}"></script>
  <script src="{%  static 'products/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{%  static 'products/js/popper.min.js' %}"></script>
  <script src="{%  static 'products/js/bootstrap.min.js' %}"></script>
  <script src="{%  static 'products/js/jquery.easing.1.3.js' %}"></script>
  <script src="{%  static 'products/js/jquery.waypoints.min.js' %}"></script>
  <script src="{%  static 'products/js/jquery.stellar.min.js' %}"></script>
  <script src="{%  static 'products/js/owl.carousel.min.js' %}"></script>
  <script src="{%  static 'products/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{%  static 'products/js/aos.js' %}"></script>
  <script src="{%  static 'products/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{%  static 'products/js/bootstrap-datepicker.js' %}"></script>
  <script src="{%  static 'products/js/jquery.timepicker.min.js' %}"></script>
  <script src="{%  static 'products/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{%  static 'products/js/google-map.js' %}"></script>
  <script src="{%  static 'products/js/main.js' %}"></script>
  </body>
</html>

brewbros/products/templates/products/details.html
{% extends 'products/base.html' %}
{% load static %}

{%  block title %}
  Product detail
{%  endblock %}
{% block body %}
{#<style>body { background-image: url({% static 'products/images/fon-22501.jpg' %}); }</style>#}
<section class="ftco-section">
  <div class="container">
    <br>
    <div class="row">
      <div class="col-lg-6 mb-5">
        <a href="#" class="image-popup"><img src="{%  static 'products/images/bag-99.jpg' %}" class="img-fluid" alt=""></a>
      </div>

      <div class="col-lg-6 product-details pl-md-5">
        <h3>{{ product.name }}</h3>
        <strong>Kind:</strong>
        <a href="{% url 'products:shop' %}">{{ product.kind }}</a>
        <br>
        <strong>Origin:</strong>
        <a href="{% url 'products:shop' %}">{{ product.origin.all|join:", " }}</a>
        <br>
        <strong>Degree of roast:</strong>
        <a href="{% url 'products:shop' %}">{{ product.profile.degree_of_roast }}</a>
        <br>
        <strong>Preparation method:</strong>
        <a href="{% url 'products:shop' %}">{{ product.profile.preparation_method }}</a>
        <br>
        <p>Price per 1kg: </p> <p class="price"><span>${{ product.price }}</span></p>

        <br>
        <div class="row mt-3">
{#          <div class="col-md-5">#}
{#            <div class="form-group">#}
{#              <div class="select-wrap">#}
{#              <div class="icon"><span class="ion-ios-arrow-down"></span></div>#}
{#                <select name="" id="" class="form-control">#}
{#                 <option value="">1kg</option>#}
{#                 <option value="">500g</option>#}
{#                 <option value="">250g</option>#}
{#                </select>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}

          <div class="w-100"></div>
              <form action="{% url 'cart:cart_add' product.id %}" method="post" class="input-group col-md-5 mt-3 mb-3">
                <span class="input-group-btn mr-2 mt-2">
                  <button type="button" class="quantity-left-minus btn"  data-type="minus" data-field="">
                    <i class="icon-minus"></i>
                  </button>
                </span>
                <input type="text" id="quantity" name="quantity" class="form-control input-number mr-2 mt-2" value="1" min="1" max="100">
                <span class="input-group-btn mr-2 mt-2">
                  <button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
                    <i class="icon-plus"></i>
                  </button>
                </span>
                  <br>
                {% csrf_token %}
                  {{  form.as_p }}
                 <input type="submit" class="btn btn-primary py-3 px-5 mt-2" value="Add to cart">
              </form>
        </div>
      </div>
    </div>
    <h4><span>Description</span></h4>
     <p>{{ product.description }}</p>
  </div>
</section>

<script src="{%  static 'products/js/jquery.min.js' %}"></script>
<script>
    $(document).ready(function(){
    var quantitiy=0;
       $('.quantity-right-plus').click(function(e){
            e.preventDefault();
            var quantity = parseInt($('#quantity').val());
           $('#quantity').val(quantity + 1);
        });
         $('.quantity-left-minus').click(function(e){
             e.preventDefault();
             var quantity = parseInt($('#quantity').val());
                if(quantity>0){
                $('#quantity').val(quantity - 1);
                }
        });
    });
</script>
{%  endblock %}

brewbros/products/templates/products/home.html
{% extends 'products/base.html' %}
{% load static %}

{%  block title %}
  Home
{%  endblock %}

{% block body %}

    <section class="home-slider owl-carousel">
       <div class="slider-item" style="background-image: url({%  static 'products/images/fon-25.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

            <div class="col-md-8 col-sm-12 text-center ">
                <span class="subheading">Special offer</span>
              <h2 class="mb-4">We give each new user a 10% discount on the first online order</h2>

            </div>
          </div>
        </div>
      </div>

      <div class="slider-item" style="background-image: url({%  static 'products/images/fon-43.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

            <div class="col-md-8 col-sm-12 text-center e">
                 <h2 class="mb-4">Coffee From All Over The World</h2>
              <p class="mb-4 mb-md-5">Get a new coffee experience</p>
            </div>
          </div>
        </div>
      </div>
    </section>

     <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section ftco-animate text-center">
{#          	<span class="subheading">Discover</span>#}
            <h3 class="mb-4">Our Coffee Bestsellers</h3>
            <p>Cup so flavour as crema redeye cultivar, body medium single origin americano rich. Sugar medium, cinnamon lungo ristretto caffeine variety foam whipped.</p>
          </div>
        </div>
        <div class="row">
        	<div class="col-md-3">
        		<div class="menu-entry">
    					<a href="#" class="img" style="background-image: url({%  static 'products/images/bag-99.jpg' %});"></a>
    					<div class="text text-center pt-4">
    						<h3><a href="#">Costa Rica</a></h3>
    						<p>Con panna fair trade seasonal arabica lungo cultivar lungo arabica </p>
    						<p class="price"><span>$25.90</span></p>
{#    						<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
    					</div>
    				</div>
        	</div>
        	<div class="col-md-3">
        		<div class="menu-entry">
    					<a href="#" class="img" style="background-image: url({%  static 'products/images/bag-99.jpg' %});"></a>
    					<div class="text text-center pt-4">
    						<h3><a href="#">Brasilia</a></h3>
    						<p>Brewed aftertaste cream, sweet galão café au lait cup variety sweet</p>
    						<p class="price"><span>$25.90</span></p>
{#    						<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
    					</div>
    				</div>
        	</div>
        	<div class="col-md-3">
        		<div class="menu-entry">
    					<a href="#" class="img" style="background-image: url({%  static 'products/images/bag-99.jpg' %});"></a>
    					<div class="text text-center pt-4">
    						<h3><a href="#">Ethiopia</a></h3>
    						<p>Skinny organic mug, arabica aromatic so carajillo beans instant</p>
    						<p class="price"><span>$25.90</span></p>
{#    						<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
    					</div>
    				</div>
        	</div>
        	<div class="col-md-3">
        		<div class="menu-entry">
    					<a href="#" class="img" style="background-image: url({%  static 'products/images/bag-99.jpg' %});"></a>
    					<div class="text text-center pt-4">
    						<h3><a href="#">Columbia</a></h3>
    						<p>Java, coffee qui medium a aromatic java iced plunger pot black</p>
    						<p class="price"><span>$25.90</span></p>
{#    						<p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
    					</div>
    				</div>
        	</div>
        </div>
    	</div>
    </section>
   <br><br><br>
    <section class="ftco-about d-md-flex">
     	<div class="one-half img" style="background-image: url({%  static 'products/images/about-2.jpg' %});"></div>
    	<div class="one-half ftco-animate">
    		<div class="overlap">
	        <div class="heading-section ftco-animate ">
{#	        	<span class="subheading">Discover</span>#}
	          <h3 class="mb-4">About Us</h3>
	        </div>
	        <div><p>Spoon skinny, est mug as, sugar a foam sugar black plunger pot. Est extra  milk robust cortado aged grounds fair trade robusta. Half and half robust in extraction aged wings dripper. Froth foam aromatic cinnamon aftertaste acerbic flavour turkish espresso.</p>
                 <p>Aged bar , robusta iced mocha white shop redeye. Mug coffee et aromatic body barista mocha seasonal espresso et roast. Java, extraction dark caramelization roast, sit grinder mocha whipped decaffeinated. Irish robusta, and crema steamed white bar , body coffee caramelization body aroma.</p>
                 <p>Coffee cinnamon, arabica froth caffeine froth beans, carajillo single shot mazagran aftertaste irish. Java crema cup, at, mazagran cortado sugar medium aromatic cultivar siphon milk. Café au lait aromatic id, cappuccino macchiato caffeine brewed barista brewed ut lungo brewed. Irish macchiato wings coffee lungo at barista.</p>
	  			</div>
  			</div>
        </div>
    </section>

    <section class="ftco-section img" id="ftco-testimony" >
    	<div class="overlay"></div>

	      <div class="row justify-content-center mb-5">
	        <div class="col-md-7 heading-section text-center ">
{#	        	<span class="subheading">Reviews</span>#}
	          <h3 class="mb-4">Customers Reviews</h3>
{#	          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>#}
	        </div>
	      </div>
{#	    </div>#}
	    <div class="container-wrap">
	      <div class="row d-flex no-gutters">
	        <div class="col-lg align-self-sm-end">
	          <div class="testimony">
	             <blockquote>
	                <p>&ldquo;Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small.&rdquo;</p>
	              </blockquote>
	              <div class="author d-flex mt-4">
	                <div class="image mr-3 align-self-center">
	                   <img src="{%  static 'products/images/ironman.jpg' %}" alt="">
	                </div>
	                <div class="name align-self-center">Tony Stark <span class="position">Iron Man</span></div>
	              </div>
	          </div>
	        </div>
	        <div class="col-lg align-self-sm-end">
	          <div class="testimony overlay">
	             <blockquote>
	                <p>&ldquo;Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.&rdquo;</p>
	              </blockquote>
	              <div class="author d-flex mt-4">
	                <div class="image mr-3 align-self-center">
	                  <img src="{%  static 'products/images/ironman.jpg' %}" alt="">
	                </div>
	                <div class="name align-self-center">Tony Stark <span class="position">Iron Man</span></div>
	              </div>
	          </div>
	        </div>
	        <div class="col-lg align-self-sm-end">
	          <div class="testimony">
	             <blockquote>
	                <p>&ldquo;Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small  line of blind text by the name. &rdquo;</p>
	              </blockquote>
	              <div class="author d-flex mt-4">
	                <div class="image mr-3 align-self-center">
	                  <img src="{%  static 'products/images/ironman.jpg' %}" alt="">
	                </div>
	                <div class="name align-self-center">Tony Stark <span class="position">Iron Man</span></div>
	              </div>
	          </div>
	        </div>
	        <div class="col-lg align-self-sm-end">
	          <div class="testimony overlay">
	             <blockquote>
	                <p>&ldquo;Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however.&rdquo;</p>
	              </blockquote>
	              <div class="author d-flex mt-4">
	                <div class="image mr-3 align-self-center">
	                  <img src="{%  static 'products/images/ironman.jpg' %}" alt="">
	                </div>
	                <div class="name align-self-center">Tony Stark <span class="position">Iron Man</span></div>
	              </div>
	          </div>
	        </div>
	        <div class="col-lg align-self-sm-end">
	          <div class="testimony">
	            <blockquote>
	              <p>&ldquo;Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small  line of blind text by the name. &rdquo;</p>
	            </blockquote>
	            <div class="author d-flex mt-4">
	              <div class="image mr-3 align-self-center">
	                 <img src="{%  static 'products/images/ironman.jpg' %}" alt="">
	                </div>
	                <div class="name align-self-center">Tony Stark <span class="position">Iron Man</span></div>
	            </div>
	          </div>
	        </div>
	      </div>
        </div>
	  </section>
  </section>

<div class="ftco-footer ftco-section img">
      <div class="container">
      <div class="col col-md-6 mb-5 mb-md-5">
        <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Have a Questions?</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">178 Mitchell Rue, Simpsonburgh, Vickyborough, UK</span></li>
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">02061077728</span></a></li>
                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
              </ul>
            </div>
        </div>
        <div>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
    </div>
</div>

{% endblock %}

brewbros/products/templates/products/shop.html
{% extends 'products/base.html' %}
{% load static %}

{%  block title %}
  Shop
{%  endblock %}

{% block body %}
{#<style>body { background-image: url({% static 'products/images/fon-22501.jpg' %}); }</style>#}
<div class="container"><br>
{#      <h5>Filter By Kind</h5>#}
{#        <div class="tagcloud">#}
{#          {% if filter_by == 0 %}#}
{#            <a class="nav-link active" aria-selected="true">All</a>#}
{#          {% else %}#}
{#            <a href="{% url 'products:shop' %}" class="tag-cloud-link" aria-selected="true">All</a>#}
{#          {% endif %}#}
{#          {% for elem in kind %}#}
{#            {% if elem.pk == filter_by %}#}
{#              <a class="nav-link active" aria-selected="true">{{ elem.name }}</a>#}
{#            {% else %}#}
{#              <a href="{{ elem.get_absolute_url }}" class="tag-cloud-link">{{ elem.name }}</a>#}
{#            {% endif %}#}
{#          {% endfor %}#}

{#      <h5>Filter By Origin</h5>#}
{#        <div class="tagcloud">#}
{#          {% if filter_by == 0 %}#}
{#            <a class="nav-link active" aria-selected="true">All</a>#}
{#          {% else %}#}
{#            <a href="{% url 'products:shop' %}" class="tag-cloud-link" aria-selected="true">All</a>#}
{#          {% endif %}#}
{#          {% for elem in origin %}#}
{#            {% if elem.pk == filter_by %}#}
{#              <a class="nav-link active" aria-selected="true">{{ elem.origin }}</a>#}
{#            {% else %}#}
{#              <a href="{{ elem.get_absolute_url }}" class="tag-cloud-link">{{ elem.origin }}</a>#}
{#            {% endif %}#}
{#          {% endfor %}#}
{#    </div>#}

 <section class="ftco-menu mb-5 pb-5">
  <div class="row">
    <div class="col col-4 col-md-3 col-lg-2">
      <div class="menu-entry">
      <form action="" method="post" class="billing-form">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" class="btn btn-primary btn-outline-primary col-11" value="filter by kind">
      </form>
      </div>
    </div>
  </div>
<br>
  <div class="row">
    {% for product in products %}
      <div class="col-md-3">
        <div class="menu-entry">
          <a href="{% url 'products:details' product.pk %}" class="img" style="background-image: url({%  static 'products/images/bag-99.jpg' %});"></a>
            <div class="text text-center pt-4">
                <h3><a href="{% url 'products:details' product.pk %}">{{ product.name.title }}</a></h3>
                <p class="text-primary">{{ product.kind }}</p>
                <p class="price"><span>${{ product.price }}</span></p>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                  <input type="hidden" id="quantity" name="quantity" class="form-control input-number" value="1">
                    {% csrf_token %}
                  <input type="submit" class="btn btn-primary btn-outline-primary px-4 mt-3" value="Add to cart">
                </form>
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</section>
</div>

{% endblock %}